// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA94Olv1qomRz8sG8XEmZepb16NE0RuUQ0',
    appId: '1:641758211040:android:e7889d5516c3edcb0e1985',
    messagingSenderId: '641758211040',
    projectId: 'todoapp-47c45',
    storageBucket: 'todoapp-47c45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx5i_gZ02ZYHRwsVJJDZKnDz7d9Kg6KGo',
    appId: '1:641758211040:ios:864d780fd85dc6e20e1985',
    messagingSenderId: '641758211040',
    projectId: 'todoapp-47c45',
    storageBucket: 'todoapp-47c45.appspot.com',
    androidClientId: '641758211040-4ob2ejb21pre4t82aljosidn89sjjsp0.apps.googleusercontent.com',
    iosClientId: '641758211040-pt72r9b1b1mv2r49ue0q3lvn3tm5jm6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
